### PR TITLE
Fix derived protocol ID so there are no double slashes

### LINKED ISSUE #86: head protocol ID ends up with double `/` for topic names starting with `/`
Example:
```
/legs/head//indexer/ingest/mainnet/0.0.1
```

https://github.com/filecoin-project/go-legs/blob/36b1633ecf46df82742c188a97f21773cb3872fc/p2p/protocol/head/head.go#L40

### PR DESCRIPTION
**Pull request by gammazero**
When the head client connects to a libp2p server and receives a "protocol not supported" error, it will try the old double-slashed protocol ID.

Fixes #86

### CODE REVIEW

File: p2p/protocol/head/head.go [hunk 1]
```diff
@@ -63,7 +63,22 @@ func QueryRootCid(ctx context.Context, host host.Host, topic string, peerID peer
 				if err != nil {
 					return nil, err
 				}
-				return gostream.Dial(ctx, host, peerID, deriveProtocolID(topic))
+				conn, err := gostream.Dial(ctx, host, peerID, deriveProtocolID(topic))
+				if err != nil {
+					// If protocol ID is wrong, then try the old "double-slashed" protocol ID.
+					//
+					// TODO: remove this code when all providers have upgraded.
+					if err.Error() != "protocol not supported" {
```
Comment (masih) [inline p2p/protocol/head/head.go:71]: I suspect the error returned is [this](https://github.com/multiformats/go-multistream/blob/master/client.go#L18), which would make it possible to check the type instead of message.

Comment (gammazero) [reply p2p/protocol/head/head.go:71]: Thank you. I thought it might be [this one](https://github.com/libp2p/go-libp2p/blob/master/p2p/protocol/identify/peer_loop.go#L21) which is not exported. After testing, looks like you are correct.

File: p2p/protocol/head/head_test.go [hunk 2]
```diff
@@ -1,12 +1,11 @@
-package head_test
+package head
```
Comment (masih) [inline p2p/protocol/head/head_test.go:1]: It would be great to keep tests in a separate package where possible. It 
* helps maintain encapsulation, and
* showcases how to use the API in tests.

For a case where some internal API needs to be exposed for testing, like `deriveProtocolID`, there is already a nice pattern to expose just enough for testing purposes which I find to work really well. This is exposing APIs in a separate `*_test.go` file that is in the `head` package then using that exposed function in `head_test` package. [Example](https://github.com/filecoin-project/index-provider/blob/main/engine/chunker/cached_chunker_api_test.go). This way we achieve best of both words: maintained encapsulation between implementation and testing, and avoid exporting unwanted API just to be able to unit test.

**Review by masih — APPROVED** [review]
